default: &default
  adapter: postgresql
  host: 127.0.0.1
  pool: 5
  username: root
  password: password
  reconnect: false

development:
  <<: *default
  database: shop_development

test:
  <<: *default
  database: shop_test

